# Generated by Django 4.2.7 on 2023-11-12 00:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='question',
            old_name='q',
            new_name='ques',
        ),
    ]
